version: '0.0.{build}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
clone_folder: c:\projects\NuGetDownloader
branches:
  only:
    - master
    - dev
skip_tags: true
cache:
  - packages -> **\packages.config
platform: Any CPU
configuration: Release
test:
  assemblies:
    - '**\*Tests.dll'
build_script:
  - ps: ./build.ps1 --target=CICD
install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php
  - choco install dotnetcore-sdk
artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: 5MSrZkoZgLIbpTNzQUZL6ZzKC9XkgNt6NZqt6q2M7ZQ=
    on:
      branch: master
