version: '1.0.{build}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
clone_folder: c:\projects\NuGetDownloader
branches:
  only:
    - master
    - dev
skip_tags: true
cache:
  - packages -> **\packages.config
configuration: Release
test:
  assemblies:
    - '**\*Tests.dll'
build_script:
  - ps: ./build.ps1 --target=CICD
install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php
  - choco install dotnetcore-sdk
artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: AZC5TeFbcA+KaGyyoQ5ig/7u06TPpCyf3YL8NjFOEPaqk6vb8+2afWAEPbaclQum
    on:
      branch: master
  - provider: NuGet
    name: production
    api_key:
      secure: AZC5TeFbcA+KaGyyoQ5ig/7u06TPpCyf3YL8NjFOEPaqk6vb8+2afWAEPbaclQum
    on:
      APPVEYOR_REPO_TAG: true
